name: NoResearch
version: '${project.version}'
main: net.guizhanss.noresearch.implementation.NoResearch
api-version: 1.14
depend: [ Slimefun ]
softdepend: [ GuizhanLibPlugin ]
authors: [ ybw0014 ]
description: A Slimefun Addon
